CREATE DATABASE IF NOT EXISTS MY_SHOP ;
USE MY_SHOP ;
CREATE TABLE OFFICES(
	O_No INTEGER PRIMARY KEY NOT NULL ,
    Town VARCHAR(15),
    Region VARCHAR (10),
    DIR INTEGER ,
    Objective INTEGER,
    Sales
    
);
-- IF YOU HAVE PROBLEMS WITH FOREIGN KEY YOU CAN CREATE TABLES AFTER ADD FOERIGN KEYS!! 